### ISSUE TITLE
We have some errors in getting API data!

### ISSUE THREAD

**Issue by Mahantor** [ErfanPY/aparatPlayListDownloader#7]
error : We have some errors in getting API data!

**Comment by ErfanPY** [comment]
I'm gonna check it out. Can you send a more detailed log message or an screenshot?

**Comment by Mahantor** [comment]
![Screenshot 2024-06-10 110121](https://github.com/ErfanPY/aparatPlayListDownloader/assets/91434001/7fbfb39b-054b-4093-889b-1f8b9c6cb25c)

**Comment by Mahantor** [comment]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\SaeID\Desktop\aparatPlayListDownloader-master11> pip3 install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: bs4 in c:\users\saeid\appdata\roaming\python\python312\site-packages (from -r requirements.txt (line 1)) (0.0.2)
Requirement already satisfied: progressbar in c:\users\saeid\appdata\roaming\python\python312\site-packages (from -r requirements.txt (line 2)) (2.5)
Requirement already satisfied: beautifulsoup4 in c:\users\saeid\appdata\roaming\python\python312\site-packages (from bs4->-r requirements.txt (line 1)) (4.12.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\saeid\appdata\roaming\python\python312\site-packages (from beautifulsoup4->bs4->-r requirements.txt (line 1)) (2.5)

[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: python.exe -m pip install --upgrade pip
PS C:\Users\SaeID\Desktop\aparatPlayListDownloader-master11> python adp.py
C:\Program Files\Python312\python.exe: can't open file 'C:\\Users\\SaeID\\Desktop\\aparatPlayListDownloader-master11\\adp.py': [Errno 2] No such file or directory
PS C:\Users\SaeID\Desktop\aparatPlayListDownloader-master11> python apd.py
usage:
        Use "" around link to avoid bad things :>
        adp.py "Link" [quality]
        python apd.py "https://www.aparat.com/v/d13rh3"
        python apd.py "https://www.aparat.com/v/d13rh3" -q 480

        The default quality is 480.

apd.py: error: the following arguments are required: link
PS C:\Users\SaeID\Desktop\aparatPlayListDownloader-master11> python apd.py "https://www.aparat.com/v/WH2wk" -q 480
Please wait...
Traceback (most recent call last):
  File "C:\Users\SaeID\Desktop\aparatPlayListDownloader-master11\apd.py", line 75, in <module>
    main()
  File "C:\Users\SaeID\Desktop\aparatPlayListDownloader-master11\apd.py", line 25, in main
    main_name = main_soup.find("span", attrs={"class":"d-in v-m"}).text.encode()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'
PS C:\Users\SaeID\Desktop\aparatPlayListDownloader-master11> python apd.py "https://www.aparat.com/v/WH2wk"
Please wait...
Traceback (most recent call last):
  File "C:\Users\SaeID\Desktop\aparatPlayListDownloader-master11\apd.py", line 75, in <module>
    main()
  File "C:\Users\SaeID\Desktop\aparatPlayListDownloader-master11\apd.py", line 25, in main
    main_name = main_soup.find("span", attrs={"class":"d-in v-m"}).text.encode()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'
